spring:
  datasource:
    username: root
    password: lzj2515628
    url: jdbc:mysql://mydb:3306/miaosha?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: HTML5 # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    check-template-location : true
    suffix: .html

  redis:
    database: 0
    timeout: 0
    port: 26379
    host: myredis
    password: luozijing@2021
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
  rabbitmq:
    host: myrabbitmq
    password: guest
    username: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000
        default-requeue-rejected: true
  web:
    resources:
      static-locations: classpath:/static/, classpath:/templates/


mybatis:
  mapper-locations: com/travel/function/mapper/*.xml
  type-aliases-package: com.travel.function.entity,com.travel.function.vo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pageCache:
  enable: true
logging:
  level:
    com.cet.diagsyscloud.system.dao: DEBUG
  file:
    name: /var/logs

zookeeper:
  address: myzookeeper:2181
  timeout: 200000

dubbo:
  application:
    name: ADMIN
  registry:
    address: nacos://81.69.254.72:8848
  config-center:
    address: nacos://81.69.254.72:8848
  metadata-report:
    address: nacos://81.69.254.72:8848
  protocol:
    name: dubbo
    port: 22385