spring:
  datasource:
    username: root
    password: lzj2515628
    url: jdbc:mysql://42.192.183.193:3306/miaosha1?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    timeout: 0
    port: 26379
    host: 42.192.183.193
    password: luozijing@2021
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        max-wait: -1
  rabbitmq:
    host: 42.192.183.193
    password: guest
    username: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000
        default-requeue-rejected: true
zookeeper:
  address: 42.192.183.193:2181
  timeout: 200000

dubbo:
  application:
    name: ORDER
  registry:
    address: nacos://42.192.183.193:8848
  config-center:
    address: nacos://42.192.183.193:8848
  metadata-report:
    address: nacos://42.192.183.193:8848
  protocol:
    name: dubbo
    port: 22383